### ISSUE TITLE
Write data to Influx

### ISSUE THREAD

**Issue by Posterminal** [paregupt/ucs_traffic_monitor#1]
After running ucs_traffic_monitor.py, I get data from UCS. How to write data from UCS to InfluxDB?

**Comment by paregupt** [comment]
Is it working for you now? If not, please check README.md now. I have updated the steps.

**Comment by Posterminal** [comment]
Thanks, its work for me. But i dont see my_logo and logo_cisco on  Welcom dashbord and another dashboards
this look like
![зображення](https://user-images.githubusercontent.com/32669832/75609188-231d9600-5b0f-11ea-9fc1-bc42eae338e7.png)

**Comment by paregupt** [comment]
Great. You have the important part working. 
The panel dynamically fetches logo from a locally hosted server. You will need to make the files accessible and use the location in the Grafana panel. See details here: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Setting_up_front-end_visualization_using_Grafana

You can personalize it further by editing (your name) in the top-most panel

Please keep me posted how it goes, any enhancements or modifications. 

Apologies for the delay in response. Cheers!
