### ISSUE TITLE
Dashboard incorrect

### ISSUE THREAD

**Issue by Posterminal** [paregupt/ucs_traffic_monitor#13]
i import new dashboard and find severel bad value in UCS Domain - Overview and Service Profile Stats
![зображення](https://user-images.githubusercontent.com/32669832/79948400-79a6b100-847c-11ea-82f6-8a3b1d7d3e79.png)
![зображення](https://user-images.githubusercontent.com/32669832/79948511-ace94000-847c-11ea-9212-f2df63dbe1cc.png)

**Comment by paregupt** [comment]
please update the ucs_traffic_monitor.py also. The 0.3 release brought in the support of C-series server. I changed naming of the database tags and field to make them neutral. For example BladeServer changes to Servers, etc.

Let me know how it goes with the new ucs_traffic_monitor.py

**Comment by Posterminal** [comment]
i use new ucs_traffic_monitor.py

**Comment by paregupt** [comment]
Looks like I forgot to update them all. Thanks for catching this.

For Location, edit the panel and use this query:
`
select location from (select location,last(fi_fw_sys_ver) from "autogen"."FIEnvStats" where ("domain" =~ /^$domain$/) AND $timeFilter)`

For the null value on the service profile page, edit the panel. Go to query E and use this:
`
select server from (select server,last(bytes_rx_delta) from "autogen"."VnicStats" where "service_profile"  =~ /^$service_profile$/ AND $timeFilter)`

**Comment by Posterminal** [comment]
For Location work thanks. For the null value on the service profile page - not working
