### ISSUE TITLE
Chassis PAUSE frame monitoring

### ISSUE THREAD

**Issue by Posterminal** [paregupt/ucs_traffic_monitor#14]
i have 3 different domain ucs, in 2 domain i see monitoring RX PAUSE but 1 domain show No data, how i can test receiving information from  ucs

**Comment by paregupt** [comment]
what are the model numbers of the FI and UCSM versions? Which of them work?

**Comment by Posterminal** [comment]
FI 6332-16UP UCSM versions 3.2(3c)  - not work 
FI 6332-16UP UCSM versions 3.2(3c)  -work (with only 40G ports)
FI 6296UP UCSM versions 4.0(4g) - work
I found a regularity, on firmware 3.2(3c) only shows 40G ports, on 10G ports not not show PAUSE frame

**Comment by paregupt** [comment]
Did it work before with the previous version?
Do you see anything at all or is everything blank?
What is connected to the FIs - 5108 chassis, FEX, etc?

You can see detailed logs by running this manually. First, stop the telegraf service.

`sudo systemctl stop telegraf
`
then

`python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv
`
Look for any errors in logfile at /var/log/telegraf/ucs_traffic_monitor/

The pause stats are collected from the `show interface priority-` command from FIs in nxos mode. You can try to compare the output of the commands on the working vs non-working domain.

When you are done troubleshooting, do not forget to delete or rename the .pickle file and logfile generated by your user account while running UTM manually. 

I will try to find a lab device with that combination tomorrow.

**Comment by Posterminal** [comment]
I see everything blank. i see "pause_rx": "1138930" in ucs_traffic_monitor_ucs_domains_group_1.log, but dashboard is everything blank. FIs connect to  5108 chassis 10Gx4.

**Comment by paregupt** [comment]
Trying to understand what you mean by 'blank'. Do you see the panel but reported values are 0, like this:

![image](https://user-images.githubusercontent.com/8773072/80009454-f1c1a680-847d-11ea-8e65-fd99dfa65bd9.png)

OR, does the panel says No data, like this

![image](https://user-images.githubusercontent.com/8773072/80009510-0605a380-847e-11ea-90dc-7e88cbf04689.png)

**Comment by Posterminal** [comment]
I see like 

![](https://user-images.githubusercontent.com/8773072/80009510-0605a380-847e-11ea-90dc-7e88cbf04689.png)

**Comment by paregupt** [comment]
need to debug it further. I can't ask you you dump the logs here on a public forum. do you have a Cisco rep or a previous cisco TAC case so that I can find your contact info and reach out to you directly? Else, you can email me: my github user id followed by cisco

**Comment by Posterminal** [comment]
i send you email

**Comment by paregupt** [comment]
Looks like the code was not handling PAUSE frames on breakout links between FI and IOMs. The commit adds the fix for this.
