### ISSUE TITLE
your_logo and cisco_logo element names do not exist

### ISSUE THREAD

**Issue by IanSJones** [paregupt/ucs_traffic_monitor#16]
Hi
Awsome work by the way - really excellent.

I am getting the text: 

<script> document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + "/your_logo.png"); </script>

for both the your_logo.png and cisco_logo.png on at least the "UCS Domain Overview" page.  The element names 'your_logo' and 'cisco_logo' do not exist.

HTH
Ian

![image](https://user-images.githubusercontent.com/7902941/80803763-2b478f80-8bab-11ea-8b2d-cf00bb44ddb0.png)

**Comment by paregupt** [comment]
These are fetched from a locally running web server. check details here: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Set-up_a_web_server

Do you still get this error?

**Comment by IanSJones** [comment]
Hello again Paresh,
I apologise, I didn't make myself very clear.  The your_logo.png and cisco_logo.png files are in the default http (port 80) location:

[utm@U01VPAALHYB0029:/var/www/html> ls
cisco_logo.png  world_map.png  your_logo.png

and I can http to port 80 and see these images (http://<server>/your_logo.png) but the issue is that they are not displaying on any of your dashboards.

The problem is that these images are not being displayed upon your dashboard (see attached image)[cid:b6985ca4-2a7f-4127-89f3-dfc5a7b56354]

I got a web developer of mine to check it and he said the statement:  document.getElementById('your_logo').setAttribute('src', 'http://' + window.location.hostname + "/your_logo.png")  is telling the page to load the graphic from http://<hostname>/your_logo.png and put it in the element called "'your_logo" and the problem is that the web page element "your_logo" has not been defined.

This is not my area of knowledge so I an only pass on what he said.

If you need any more information then please, do not hesitate to ask - it's the least I can do after benefitting from your excellent work.
All the very best,
Ian



________________________________

**Comment by paregupt** [comment]
Hi Ian

Glad to know UTM is of your use.

Did you also edit /etc/grafana/grafana.ini and add disable_sanitize_html = true.

See more at: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Install_Grafana_plugins

Unfortunately, web development is outside my area of expertise. I looked on the web and added this code. If it is not too much to ask from your friend, can he suggest a fix?

**Comment by paregupt** [comment]
Changing the disable_sanitize_html = true fixed this issue. Be aware: Grafana disabled it for a reason. If you are not comfortable with this change, please disable it. It is a nice-to-have feature. The core functionality is not impacted in lack of this.
