### ISSUE TITLE
Null response from a UCS causing ucs_traffic_monitor.py to bomb out

### ISSUE THREAD

**Issue by IanSJones** [paregupt/ucs_traffic_monitor#17]
Hi,
Awesome work by the way!  I was having issues with the ucs_traffic_monitor.py failing:
if per_fi_port_dict['if_role'] == 'server':  -  missing key

It turned out to be because we are receiving null data.  I have written a fix that's attached.
HTH
Ian

[ucs_traffic_monitor.py.txt](https://github.com/paregupt/ucs_traffic_monitor/files/4564102/ucs_traffic_monitor.py.txt)

**Comment by paregupt** [comment]
Hi Ian

What is the exact issue? Also, can you please add the fix here? I am unable to locate changes in the attached file.

cheers!

**Comment by IanSJones** [comment]
Hello Paresh,
I found that after a number of per_fi_port_dict pieces of data were processed that I would then receive a blank line or a null or something.
If I put a print(fi_port_dict) then the last record was a {}
Then the statement:
               if per_fi_port_dict['if_role'] == 'server':
                    fi_port_prefix = fi_server_port_prefix
                else:
                    fi_port_prefix = fi_uplink_port_prefix
would fail because the 'if_role' element was not there, the dictionary is null.  My change is as follows:

                if 'if_role' in per_fi_port_dict:
                   if per_fi_port_dict['if_role'] == 'server':
                       fi_port_prefix = fi_server_port_prefix
                   else:
                       fi_port_prefix = fi_uplink_port_prefix
                   fi_port_prefix = fi_port_prefix + domain_ip
                   fi_port_fields = fi_port_fields + '\n'
                else:
                   fi_port_prefix=''
                   fi_port_tags=''
                   fi_port_fields=''

I attach the source here as well.  I suggest you do a diff between my code and yours to see the other minor changes I have made.  I am running your code "in production" now and am happy with it's resilience.  If you would like me to do this then just ping me.
Best regards,
Ian

________________________________

**Comment by paregupt** [comment]
Hi Ian

Thanks for your response. I suspect that the original root cause may be something else. It just crashes here due to absence of if_role. This should be debugged further and fixed gracefully. Your change may be masking the error, not really fixing it.

You may email me at my github id followed by at cisco. We can have a webex to troubleshoot it.

Thanks

**Comment by IanSJones** [comment]
Yes, I thought perhaps there had been a firmware change or something but I am more than happy to help.  If you want to send me a Webex invite (or I'll send one to you) then we can work on it now if that is convenient?

________________________________

**Comment by paregupt** [comment]
Issue with UCS mini
