### ISSUE TITLE
New setup issue with python script

### ISSUE THREAD

**Issue by chadelard** [paregupt/ucs_traffic_monitor#18]
Hello thanks for putting this app together, it looks great! I'm having an issue with setting up new domains for first time use. I downloaded your .3 OVA and deployed it as you described which worked great. Here is the error I'm seeing in the ucs_traffic_monitor_ucs_domains_group_1.log

2020-05-06 09:47:20,977 - ERROR - Exception with print_output:'transport'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2698, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2653, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2371, in print_output_in_influxdb_lp
    ',transport=' + per_fi_port_dict['transport']
KeyError: 'transport'
2020-05-06 09:47:20,978 - INFO - Pickle sessions for next time in /usr/local/telegraf/ucs_traffic_monitor_ucs_domains_group_1.pickle : {'10.208.133.50': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7f866eabf6d8>, 'sdk_time': 1588771933, 'cli': None}, '10.184.99.100': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7f866eabfa58>, 'sdk_time': 1588772295, 'cli': None}, '172.26.92.10': {'sdk': <ucsmsdk.ucshandle.UcsHandle object at 0x7f866eabfb70>, 'sdk_time': 1588767016, 'cli': None}}
2020-05-06 09:47:20,979 - INFO - 
    |--------------------------------------------|
    |        Response time - 10.208.133.50       | 
    |--------------------------------------------|
    | CLI: Login:     5.6 s  | Query:    7.32 s  |
    | SDK: Login:    0.41 s  | Query:    5.51 s  |
    | Total:    12.92 s                          |
    |--------------------------------------------|
    |--------------------------------------------|
    |        Response time - 10.184.99.100       | 
    |--------------------------------------------|
    | CLI: Login:    6.76 s  | Query:    6.76 s  |
    | SDK: Login:    1.16 s  | Query:    6.95 s  |
    | Total:    13.52 s                          |
    |--------------------------------------------|
    |--------------------------------------------|
    |        Response time - 172.26.92.10        | 
    |--------------------------------------------|
    | CLI: Login:     9.3 s  | Query:    8.63 s  |
    | SDK: Login:    2.79 s  | Query:   10.18 s  |
    | Total:    17.93 s                          |
    |--------------------------------------------|
    |--------------------------------------------|
    |          Time taken to complete            |
    |--------------------------------------------|
    |                           Input:  2.773 s  |
    | Connection setup and stats pull: 17.933 s  |
    |                         Parsing:  0.016 s  |
    |                          Output:  0.002 s  |
    |------------------------------------------  |
    |                           Total: 20.724 s  |
    |--------------------------------------------|
2020-05-06 09:47:20,979 - WARNING - ---------- END ----------

**Comment by paregupt** [comment]
What is the UCSM version and FI model? Do you have any other UCS domain that works?

**Comment by chadelard** [comment]
One location is running 6248's and running 4.0.4d. The other two are UCS Mini's running the same firmware on 6324's

**Comment by chadelard** [comment]
No, none of the locations are working. Here is what I have configured. The /var/log/telegraf/telegraf.log is empty

[root@US01-UCSMON01 telegraf]# cat ucs_domains_group_1.txt 
# Add new domain in format:IP_Address,username,password
# Add comma between items
# Do not leave whitespaces between items
# Do not leave an empty line
# Lines starting with # are ignored
# Text between [] is location
#[US]
#192.168.1.1,admin,passwd
#[UK]
#192.168.1.1,admin,passwd
#[Italy]
#192.168.1.1,admin,passwd
#[China]
#192.168.1.1,admin,passwd
[US14]
10.208.133.50,monitor,UCS-password-RO
[DE01]
10.184.99.100,monitor,UCS-password-RO
[IN01]
172.26.92.10,monitor,UCS-password-RO

**Comment by chadelard** [comment]
Also, the audit logs on all three of the UCSM are showing successful logins every minute and then logoffs after ~15 seconds.

**Comment by paregupt** [comment]
Can you please try with 6248 only? Remove the UCS mini and check?

**Comment by chadelard** [comment]
Yes that seems to fix the issue with the 6248 site. Are the 6324's not able to be monitored then?

**Comment by paregupt** [comment]
Thanks for the verification. This is the same issue as #17. I do not have UCS mini in my lab. Trying to find a working environment. Will keep you updated. Until then, you may want to skip the minis.
