### ISSUE TITLE
FCS Errors?

### ISSUE THREAD

**Issue by exbane** [paregupt/ucs_traffic_monitor#2]
Good morning! 

This collector is fantastic! I've been able to setup it up for the 8 different UCS infrastructures that i manage. 

Question - is there a way to poll FCS errors from the FI Server Ports? Typically whenever i see the FCS error stats start to creep up it means there's a bad twinax cable every time.  Being able to view these types of errors would be awesome in Grafana. 

Thank you! 

exbane

**Comment by paregupt** [comment]
Exbane, good to know that it is working for you. If you have a wishlist, please open issues here to track them. No primises but you never know..

Regarding your question - UTM receives FCS counters but does not store them in the database. It should be a simple change to store and show on Grafana. I will find some time over the weekend to make it work. BTW, can you please share how you monitor these counters today? Any CLI or GUI screen? Just to be sure that you and I are on the same page and talking about the same counter.

**Comment by exbane** [comment]
@paregupt - Thanks for the quick response! 

I will definitely add some wishlist items. 

<img width="376" alt="FCS" src="https://user-images.githubusercontent.com/12447405/76012466-53d14700-5ee4-11ea-81cc-7a242a0d64fa.PNG">

Here is a screenshot of the Counter i look at per server chassis port on the FIs. Currently i have no of monitoring these stats without manually going through each port and checking them.. Or if i start to see massive latency in my VM infrastructure that's one of the check-list items I look at. It is by far not a good way of doing it! I just haven't had time to put something together to track it properly! 

Anything you can do would be greatly appreciated! 

Thank you,

exbane

**Comment by paregupt** [comment]
ok, we have those and other counters coming into the UTM, juts need to store into DB and show on Grafana. Stay tuned...

**Comment by paregupt** [comment]
878aefa4dfebc6176585fd89c3a22106bcb430bb
