### ISSUE TITLE
Password incorrect

### ISSUE THREAD

**Issue by tjanitsc** [paregupt/ucs_traffic_monitor#21]
Hi,
the software doesnt accept the password. I'm using utm and root with the password Utm_12345 for the first time, but no success.

**Comment by paregupt** [comment]
Just curious, did it work?

**Comment by tjanitsc** [comment]
Login works, there was keyboard mistake.

Tim

Von meinem iPhone gesendet

Am 14.06.2020 um 16:21 schrieb Paresh Gupta <notifications@github.com>:

﻿

Just curious, did it work?
