### ISSUE TITLE
Locations screen shows all domains, not just for current selected location

### ISSUE THREAD

**Issue by bakins929** [paregupt/ucs_traffic_monitor#26]
I select a location from drop-down on top, it shows correct count under UCS Domains, but directly under, in # domains - [LOCATION], it shows all domains, even though it says the name of the location selected.  In the screenshot attached, the counter should show 2 instead of 3.
![2020-06-23 08_46_07-Locations - Grafana](https://user-images.githubusercontent.com/66968857/85406378-b734c280-b52f-11ea-9efa-3b6a5a0bc57e.png)

**Comment by paregupt** [comment]
Please take the mouse over the # domains panel. From the drop-down, click Edit. There should be a query starting with select..... Can you please share that?

**Comment by bakins929** [comment]
`select count(domain) from (SELECT last("model") FROM "autogen"."FIEnvStats" WHERE $timeFilter GROUP BY domain)`

**Comment by paregupt** [comment]
`select count(domain) as "# Domains" from (SELECT last("model") FROM "autogen"."FIEnvStats" WHERE "location" =~ /^$location$/ and $timeFilter GROUP BY domain)`

Please use above. Verify and save the dashboard. Using `as "# Domains"` is optional. The real fix is `"location" =~ /^$location$/`

**Comment by bakins929** [comment]
Works perfectly!  Thank you!

**Comment by paregupt** [comment]
Great.
