### ISSUE TITLE
Changing "Your logo here" 

### ISSUE THREAD

**Issue by bynet** [paregupt/ucs_traffic_monitor#27]
Hi, 

Can someone please elaborate a bit more on how to replace "Your logo here" with my own png file.
Thank you

**Comment by paregupt** [comment]
Please copy your_logo.png to /var/www/html. Overwrite the existing file. Details are here: https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/

**Comment by bynet** [comment]
Thank you working like a charm.

**Comment by paregupt** [comment]
Glad it worked. No pressure but if you can, please help the community by reporting the FI and UCSM version. The information can be shared here: https://github.com/paregupt/ucs_traffic_monitor/issues/11.

Here you can find the commands to pull this information (scroll down): https://github.com/paregupt/ucs_traffic_monitor/blob/master/working_fi_model_and_ucsm_versions.md

**Comment by paregupt** [comment]
@bynet thanks.
