### ISSUE TITLE
Possible incompatibility with UCS v4.1(1c) on 6296

### ISSUE THREAD

**Issue by jon-ae** [paregupt/ucs_traffic_monitor#28]
With a recent row upgrade to 4.1(1c), the following error occurs (I've updated script v0.41, same fail):

2020-06-23 13:58:56,824 - INFO - Parse pause stats for ucs, UCS-FI-6296UP
2020-06-23 13:58:56,827 - INFO - Done: Parse pause stats for ucs
2020-06-23 13:58:56,827 - INFO - FI - B
2020-06-23 13:58:56,827 - INFO - Stats type - pfc_stats
2020-06-23 13:58:56,827 - INFO - Parse pause stats for ucs, UCS-FI-6296UP
2020-06-23 13:58:56,830 - INFO - Done: Parse pause stats for ucs
2020-06-23 13:58:56,830 - INFO - Printing output in InfluxDB Line Protocol format
2020-06-23 13:58:56,832 - ERROR - Exception with print_output:'fi_id'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2754, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2708, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2590, in print_output_in_influxdb_lp
    ',fi_id=' + per_bp_port_dict['fi_id']
KeyError: 'fi_id'

**Comment by paregupt** [comment]
I have a FI 62xx working in lab with 4.1(1b). May be 4.1(1c) changes the data format. Need to be troubleshooted.

You can try:

- Stop telegraf or at least stop telegraf from running ucs_traffic_monitor.py
`systemctl stop telegraf`
- Manually run the utility and output the data in dictionary format. Send the output to a file and verify it.

`$ python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv`

Then check the log file in /var/log/telegraf/ucs_traffic_monitor. Look for any crashes. If not, the output data from UCSM may have changed. I can take a look in your environment. I don't have 62xx with 4.1(1c) in my lab.

**Comment by paregupt** [comment]
few hours back bynet reported 4.1(1c) working with UCS-FI-6248UP. Check this https://github.com/paregupt/ucs_traffic_monitor/issues/11#issuecomment-648213147

**Comment by jon-axp** [comment]
Hi Paresh:

I ran the execution directly and did not get any error.  The output above is from the ucs_traffic_monitor/ucs_traffic_monitor_ucs_domains_group_2.log

**Comment by paregupt** [comment]
I will need to take a look into the system. You can try attaching the complete log file here. Please do not attach anything sensitive.

**Comment by jon-axp** [comment]
Attached full output.

[ucstm-r4-output.txt](https://github.com/paregupt/ucs_traffic_monitor/files/4822019/ucstm-r4-output.txt)

**Comment by paregupt** [comment]
This log file does not have detailed logs. Please run 

`python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv`

manually. Do not forget -vvv option to enable maximum debug. You can stop the telegraf service for now.

**Comment by jon-axp** [comment]
Hi Paresh:  Additional debug output....
[ucstm-r4-output-dbug.txt](https://github.com/paregupt/ucs_traffic_monitor/files/4822180/ucstm-r4-output-dbug.txt)

**Comment by paregupt** [comment]
Analysis of the logs show that for some reason the backplane ports can't be properly populated from chassis-17. I need to troubleshoot it in your environment over webex. Is that possible? For now, as a workaround, please try the attached version. Please replace this version with the current version. The location should be /usr/local/telegraf if you are using OVA. This is not a fix, just ignoring that error.

[ucs_traffic_monitor_0.41-jon-axp.zip](https://github.com/paregupt/ucs_traffic_monitor/files/4855334/ucs_traffic_monitor_0.41-jon-axp.zip)

**Comment by paregupt** [comment]
@jon-axp did you get a chance to try it? I am taking this week a bit easy at work so if you are open for me to take a look...

**Comment by jon-axp** [comment]
Hi Paresh, sorry for the delay.  I've not tried yet, will use .41 tonight and test and If you are able, I can do a Webex at 3PM tomorrow 6/7.

**Comment by paregupt** [comment]
Tomorrow 3 works. Can you please drop me a note to my email (same as GitHub id) to setup webex?
