### ISSUE TITLE
wrong IP address after installation

### ISSUE THREAD

**Issue by bynet** [paregupt/ucs_traffic_monitor#29]
During OVA deployment. 
Have fill all IPs requirement.
Ova deployment was successful but IP is set to DHCP !
which interface should configure to static , no ifcfg-eth0 

Thank you

**Comment by paregupt** [comment]
Thanks for reporting this. You would have to change this setting manually later. I will try to fix this in the future but the UTM v0.3 OVA is already out.

**Comment by bynet** [comment]
no problem, can you please let me know which interface to modify.

**Comment by paregupt** [comment]
I  would start with `nmcli` command. I can't call myself an expert in Linux sysadmin tasks. You are better off referring to articles on the web to make this change. The VM is based on CentOS 7.6. So all standard CentOS functions/commands should work.

**Comment by kebrant** [comment]
> no problem, can you please let me know which interface to modify.

For my deployment, the interface was ens192. Modify /etc/sysconfig/network-scripts/ifcfg-ens192 file.

**Comment by bynet** [comment]
Thank you just did by using nmtui, and restarting network. I'm good. 
Just for your information paregup, 
Before that i made the change I used the nmcli command and I saw that DNS was wrong. don't know from where this IP came from....

**Comment by paregupt** [comment]
@bynet Thanks for reporting this. I need to do better next time while building the OVA. 
@kebrant thanks for the help

**Comment by bynet** [comment]
great job you did here with that UTM. 
will it be possible to add HX-Connect ? in next version ?

**Comment by paregupt** [comment]
No plans yet. Need to find time.
