### ISSUE TITLE
ERROR - Exception with print_output: 'oper_speed'

### ISSUE THREAD

**Issue by exbane** [paregupt/ucs_traffic_monitor#3]
Good morning! 

So I was inputting my last UCS which is in our new datacenter and came across this error when attempting to collect from it. 

```
2020-03-10 11:01:21,755 - ERROR - Exception with print_output:
'oper_speed'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2022, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 570, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 316, in print_output_in_influxdb_lp
    'oper_state="' + (str)(per_fi_port_dict['oper_state']) + '"'
KeyError: 'oper_speed'
```

Any thoughts?

**Comment by paregupt** [comment]
Thanks for reporting this issue. Looks like the operational speed of one of the ports is missing. I can mask this error easily but wondering what is different about this UCS.

Also, you can try this:
1. Stop telegraf or at least stop telegraf from running ucs_traffic_monitor.py
2. Manually run the utility and output the data in dictionary format. Send the output to a file and verify it.

`$ python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv
 > output_file`

Finally, if you have some time, we can look into this issue live in your environment. It really depends on the input data which may have a further dependency on HW and SW versions. I can set up a WebEx if that works for you.

BTW, I have fixed #2 , whenever you are ready to absorb the change.

**Comment by privaldi** [comment]
I as well am having this issue.

if it helps I am running ucsm 4.0.4g

.compute.ComputeBlade.ComputeBlade object at 0x7f433c06e6d8>]}}
2020-03-18 17:53:50,978 - ERROR - Exception with print_output:
'oper_speed'
Traceback (most recent call last):
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 2022, in main
    print_output()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 570, in print_output
    print_output_in_influxdb_lp()
  File "/usr/local/telegraf/ucs_traffic_monitor.py", line 316, in print_output_in_influxdb_lp
    'oper_state=' + (str)(per_fi_port_dict['oper_state']) + '"'
KeyError: 'oper_speed'

**Comment by privaldi** [comment]
I have also verified that when using ` python3.6 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt influxdb-lp -vvv
` with ucsm 4.0(1c) the data is outputted as expected.


bp_port=2/PC-1296,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
BackplanePortStats,domain=
,bp_port=2/PC-1299,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
BackplanePortStats,domain=,bp_port=2/PC-1301,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
BackplanePortStats,domain=,bp_port=2/PC-1302,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
BackplanePortStats,domain=bp_port=2/PC-1304,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
BackplanePortStats,domain=,bp_port=2/PC-1307,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"

**Comment by privaldi** [comment]
> I have also verified that when using `python3.6 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt influxdb-lp -vvv` with ucsm 4.0(1c) the data is outputted as expected.
> 
> bp_port=2/PC-1296,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
> BackplanePortStats,domain=
> ,bp_port=2/PC-1299,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
> BackplanePortStats,domain=,bp_port=2/PC-1301,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
> BackplanePortStats,domain=,bp_port=2/PC-1302,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
> BackplanePortStats,domain=bp_port=2/PC-1304,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"
> BackplanePortStats,domain=,bp_port=2/PC-1307,chassis=chassis-2,fi_id=B,fi_server_port=PC-1154 speed=10,oper_state="up"

influxdb-pl output has errors as follows:

Error in plugin: metric parse error: expected field at 2:165: "FIServerPortStats,domain

telegraf:

 [inputs.exec] Error in plugin: exec: signal: terminated for command 'python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt influxdb-lp -vvv':

**Comment by paregupt** [comment]
I have a fix for oper_speed issue but waiting for some more bake-off before the commit. Can you please use the attached ucs_traffic_monitor.py
[ucs_traffic_monitor.zip](https://github.com/paregupt/ucs_traffic_monitor/files/4352519/ucs_traffic_monitor.zip)
I will commit after your verification.

About the metric parse error, can you please share the complete output? Feel free to hide any sensitive information. If you are still not comfortable to share the info on a public forum, let me know and I will find a way to transfer the logs securely.

**Comment by privaldi** [comment]
> I have a fix for oper_speed issue but waiting for some more bake-off before the commit. Can you please use the attached ucs_traffic_monitor.py
> [ucs_traffic_monitor.zip](https://github.com/paregupt/ucs_traffic_monitor/files/4352519/ucs_traffic_monitor.zip)
> I will commit after your verification.
> 
> About the metric parse error, can you please share the complete output? Feel free to hide any sensitive information. If you are still not comfortable to share the info on a public forum, let me know and I will find a way to transfer the logs securely.

This work! Thank you for all you effort!

**Comment by paregupt** [comment]
Great. Thanks for the verification.

Just to be clear, are both the errors fixed now?

**Comment by paregupt** [comment]
878aefa4dfebc6176585fd89c3a22106bcb430bb
