### ISSUE TITLE
API Question.

### ISSUE THREAD

**Issue by bynet** [paregupt/ucs_traffic_monitor#30]
Does UTM has its own API ? 
can we reach it ?

Thank you

**Comment by eminchen** [comment]
UTM is based on Grafana and you can find API  reference here https://grafana.com/docs/grafana/latest/http_api/

On Jun 28, 2020, at 6:05 AM, bynet <notifications@github.com> wrote:

﻿

Does UTM as its own API ?
can we reach it ?

Thank you

**Comment by paregupt** [comment]
@bynet what is your end goal?

**Comment by bynet** [comment]
We would like UTM to be main system to retrieve error from instate of using multiple console such as UCSM /HX-Connect / VCenter.

Michael Zenouda
PS Computing Team Leader & Cisco UCS SME | Bynet Data Communication
Mobile: 972-52-5528207 | Fax: 972-3-5480193 | Email: Michaelz@bynet.co.il<mailto:michaelz@bynet.co.il>
Twitter: @vMzen<https://twitter.com/vMzen>

[cid:image001.jpg@01D64D6A.6F1DE2B0][cid:image002.png@01D64D6A.6F1DE2B0]

**Comment by paregupt** [comment]
Ok. The infra is built to add support for HX, vCenter, etc. However, the data needs to be brought in the DB and correlated. Few other users have asked for this before. I know how to do this but don’t have time to implement it yet. Do you or someone in your team have some cycles to contribute? I am looking for Python and vCenter api skills.
