### ISSUE TITLE
Company logo addition

### ISSUE THREAD

**Issue by ucsadmin11** [paregupt/ucs_traffic_monitor#31]
Hi, 

Really thankful for this wonderful tool. 
Can u help with adding company logo? Steps or guild lines?

**Comment by paregupt** [comment]
Check #27

**Comment by paregupt** [comment]
did it work?

**Comment by ucsadmin11** [comment]
Yes. It's working great. Many thanks

I was just tuning and by mistake deleted panel of "number of chassis". Can
u please share that query?

**Comment by paregupt** [comment]
This is the query used in UCS domain - Overview dashboard
`
select sum(count) from (select count(distinct(chassis)) from (SELECT last("model") FROM "autogen"."Servers" WHERE ("domain" =~ /^$domain$/ AND chassis!='') AND $timeFilter GROUP BY service_profile,domain,chassis,id) group by domain)`

**Comment by ucsadmin11** [comment]
Many thanks. God bless you.
