### ISSUE TITLE
Unsupported Chassi

### ISSUE THREAD

**Issue by Tidebinder** [paregupt/ucs_traffic_monitor#34]
![image](https://user-images.githubusercontent.com/38385104/87573617-93364e00-c6a3-11ea-9fd5-4917b63e6957.png)
I'm trying to add a new UCS Domain, but it has a UCSME-4308 on it, and it's making this domain to not show on the Grafana

**Comment by paregupt** [comment]
Isn't this near to the end of its support life? 
I need to look at this in your environment. Can you please drop me an email to my cisco email (same as github id)?

**Comment by paregupt** [comment]
Closing this issue. No plans to add support of UCS ME: https://www.cisco.com/c/en/us/support/servers-unified-computing/ucs-m4308-modular-chassis/model.html.
