### ISSUE TITLE
No data output at all, 6296 4.0(4g), debug inside

### ISSUE THREAD

**Issue by andrico21** [paregupt/ucs_traffic_monitor#35]
Tried to setup your solution for the first time, got no success:
manual run of the script with -vvv option shows tons of 
... not found in fi_port_dict for dc4-ucs1.m.company.name
...Unable to find chassis or FEX with id ...

[dc4-ucs1.m.company.net.txt](https://github.com/paregupt/ucs_traffic_monitor/files/5123185/dc4-ucs1.m.company.net.txt)

**Comment by paregupt** [comment]
The log file shows this:

`unable to login to dc4-ucs1.m.company.name in 10 seconds`

Can you please change CONNECTION_TIMEOUT to 30, like this:

`CONNECTION_TIMEOUT = 10`

line 27 in ucs_traffic_monitor.py and try it again?

**Comment by andrico21** [comment]
@paregupt done, see new 
[dc4-ucs1.m.company.net_30secTimeout.txt](https://github.com/paregupt/ucs_traffic_monitor/files/5124314/dc4-ucs1.m.company.net_30secTimeout.txt)
log

**Comment by paregupt** [comment]
Still, the same issue. For some reason the UCS domain is unable to open a SDK/API connection within 30 seconds. The SSH connection is working fine though. Few points:

1. Do you have any other UCS domain to try?
2. You may want to try to run this manually without any timeout value. For example:

`$date; python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv;date`

The date command before and after the UTM receiver will tell the duration to open the connection. I hope there are no firewalls in between the UTM server and the UCS domain which may be blocking port 443.

**Comment by andrico21** [comment]
Okay, now resolved one of the primary issues: only ssh was opened, not 443...
some measurements arrived, but only part of total set...
> use UCSMetrics
Using database UCSMetrics
> show measurements
name: measurements
name
----
BackplanePortStats
FIEnvStats
FIServerPortStats
FIUplinkPortStats
Servers
VnicStats
cpu
disk
diskio
kernel
mem
net
processes
swap
system

[dc4-ucs1.m.company.txt](https://github.com/paregupt/ucs_traffic_monitor/files/5125210/dc4-ucs1.m.company.txt)

**Comment by paregupt** [comment]
Great! I see all the 6 measurements. Also, the logs indicate that the receiver is working fine. Please verify the Grafana dashboards and report if anything is missing.

**Comment by andrico21** [comment]
> Great! I see all the 6 measurements. Also, the logs indicate that the receiver is working fine. Please verify the Grafana dashboards and report if anything is missing.

oh, are these all the measurements which are collected now? I thought there should be something about pauses at least (which are my primary goal to see) :)

if they're all expected metrics - we can close this particular issue now :)

**Comment by paregupt** [comment]
The PAUSE frames are under BackplanePortStats and FIServerPortStats. They are shown on almost all the dashboards based on the location of the port. There are 2 dedicated dashboards to drill down into the root cause of congestion. They should all be working now. If not, please feel free to open a new issue.
