### ISSUE TITLE
Missing "s" or "l" on service profile name if a service profile name start with an "s" or an "l"

### ISSUE THREAD

**Issue by bouthib** [paregupt/ucs_traffic_monitor#36]
Hi,

First we really appriciate what you have done so far.  Very nice work!

We found a small issue if a service profile name start with an "s" or an "l".  The "s" or "l" is missing ("lab01" would become "ab01").  It does not affect any other name.

I will submit you a pull request which should fix the issue.

Regards,

**Comment by paregupt** [comment]
Thanks for finding and fixing this issue. The changes look good.
