### ISSUE TITLE
Error in plugin: metric parse error

### ISSUE THREAD

**Issue by Zygot** [paregupt/ucs_traffic_monitor#49]
Hello, i have are next problem  

No data write to influxdb, even no table are created, I'm try DYI and OVA.

This error is repeated each min.
/var/log/telegraf/telegraf.log
[inputs.exec] Error in plugin: metric parse error: expected tag at 1:49: "FIEnvStats,domain=10.106.48.71,fi_id=A,location= load=0.130000,total_memory=32128,mem_available=27008,model=\"UCS-FI-6332-16UP\",serial=\"DELETED\",oob_if_ip=\"10.106.48.69\",mode=\"cluster\",name=\"CLUSTER_NAME\",ucsm_fw_ver=\"4.0(4g)\",fi_fw_sys_ver=\"5.0(3)N2(4.04e)\",sys_uptime=24886710"

i replace serial number and cluster name

grafana-7.1.5-1.x86_64.rpm 
influxdb-1.8.3.x86_64.rpm 
telegraf-1.17.0-1.x86_64.rpm
ucs_traffic_monitor.py v.0.47
CentOS Linux release 7.9.2009 (Core)
Linux 3.10.0-957.el7.x86_64

UCS Firmware 4_0_4g

**Comment by paregupt** [comment]
Can you please make sure the format of input file is correct? Especially: 
Text between [] is location. At least one location is mandatory.

**Comment by Zygot** [comment]
> Can you please make sure the format of input file is correct? Especially:
> Text between [] is location. At least one location is mandatory.

[[inputs.exec]]
   interval = "60s"
   commands = [
       "python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt influxdb-lp -vv",
   ]
   timeout = "50s"
   data_format = "influx"

**Comment by Zygot** [comment]
> Can you please make sure the format of input file is correct? Especially:
> Text between [] is location. At least one location is mandatory.

Thanks you!
