### ISSUE TITLE
Service Proflie - Name Cut

### ISSUE THREAD

**Issue by primip** [paregupt/ucs_traffic_monitor#51]
Hi 
In the "Service Profile" selection our names are cut by the first letter. We call our ESX Hosts like shatvi0274pp. 
From all 32 Servers the "s" is cut.

**Comment by paregupt** [comment]
Have you upgraded to the latest version? See if your issue is same as #36

**Comment by paregupt** [comment]
I am closing this issue assuming that you were able to resolve it. Feel free to open it again if you are still running into the same problem.
