### ISSUE TITLE
Usability in General

### ISSUE THREAD

**Issue by primip** [paregupt/ucs_traffic_monitor#52]
This tool is just a perfect implementation!!! It is awesome! 
But one usability issue we have is, on "Locations", "UCS Domain Overview", "Server Traffic" 
The red big squares, the numbers are very hard to read and i think the unit needs to be as well there. GB or MB/s - whatever

But that would help a lot and makes reading much easier. 

Thank you

**Comment by paregupt** [comment]
Can you please share a screenshot?

**Comment by paregupt** [comment]
I am closing this issue assuming that you were able to resolve it. Feel free to open it again if you are still running into the same problem.
