### ISSUE TITLE
Seeing Parsing errors

### ISSUE THREAD

**Issue by s405121** [paregupt/ucs_traffic_monitor#54]
Hi There,

I been following documentation from this site (https://www.since2k7.com/blog/2020/02/29/cisco-ucs-monitoring-using-grafana-influxdb-telegraf-utm-installation/#Download_and_install_Telegraf) for setting up telegraph, and InfluxDB in-order to scrape UCS metrics using this plugin and is consistently failing with below error message.

Am getting response from UCS, when running this command (python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains.txt dict -vvv) manually. Any insights on what I should look into next towards solving the issue, will be of great help.

2021-04-03T01:38:20Z E! [inputs.exec] Error in plugin: metric parse error: expected tag at 1:51: 
2021-04-03T01:38:20Z E! [telegraf] Error running agent: input plugins recorded 1 errors

Thanks,

Chaitanya Kosaraju

**Comment by paregupt** [comment]
Check #49. Did you miss mentioning location in the input file? At least one location is mandatory.

**Comment by s405121** [comment]
Thank you very much for getting back so quickly sir!! I did have that line commented out and things are working as expected after I corrected that one.

Also thank you for taking time to develop this plugin, very helpful!!

Chaitanya Kosaraju

**Comment by paregupt** [comment]
Glad it's helping you. Thanks a
