### ISSUE TITLE
Grafana shows "No Data" but data is in Influx 

### ISSUE THREAD

**Issue by amosisreal** [paregupt/ucs_traffic_monitor#55]
Deployed via OVA.
Succesfully upgraded all without errors.
Modified /var/log/telegraf/ucs_traffic_monitor/ucs_traffic_monitor_ucs_domains_group_1.log  for my UCS domain

No errors in `tail -f /var/log/telegraf/ucs_traffic_monitor/ucs_traffic_monitor_ucs_domains_group_1.log`
Looks like its connecting properly to both FI, gathering data across many objects.

Influx being populated
ex.  (other tables are populated also)
influx -database telegraf
Connected to http://localhost:8086 version 1.7.10
InfluxDB shell version: 1.7.10
> select * from system
name: system
time                host load1 load15 load5 n_cpus n_users uptime uptime_format
----                ---- ----- ------ ----- ------ ------- ------ -------------
1618490590000000000 UTM  0.43  0.04   0.12  8      0       44      0:00
1618490600000000000 UTM  0.36  0.04   0.12  8      0       54      0:00
1618490610000000000 UTM  0.31  0.04   0.11  8      0       64      0:01
1618490620000000000 UTM  0.26  0.04   0.11  8      0       74      0:01
...

When I navigate to IP_of_VM:3000 i can log in just fine, but all tables/dashboards say 'No Data'

Checking Grafana settings > Data Sources / InfluxDB I see it there and when I click Save and Test I get the modal saying "Data Source Is Working"

Tried removing and re-adding the datasource, still not populating data.

**Comment by amosisreal** [comment]
Looks like i spoke too soon - the populated tables are the CENTOS metrics.  Need to research why the python script is not updating into Influx from my connected domain.

**Comment by amosisreal** [comment]
Feel free to delete this issue.
The UCSMSDK queries were being sent from Centos through Proxy when the UCS domain needed to be excluded from proxy.  
SSH/Paramiko was working and returning information in the logs which I interpreted as the UCSMSDK connection.

Once I added the UCSM domain ip to my no_proxy settings, everything started working properly.

Thanks!

**Comment by paregupt** [comment]
Glad it worked!
