### ISSUE TITLE
Error in plugin: metric parse error

### ISSUE THREAD

**Issue by vevdokimov04041976** [paregupt/ucs_traffic_monitor#57]
Hello Paresh,
We got next error after installation and configuration according your description:
2021-05-20T14:13:21Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 210:225: "VnicStats,domain=10.X.X.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=esx3,transport=Eth,vif_name=dynamic-prot-001,peer_type=IOM,peer=IOM-1,peer_port=1/13,fi_id=A "

Running the command "python3.6 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt dict -vvv" does not show any errors. 
Just only:
2021-05-20 16:42:01,175 - DEBUG - In vnic_stats for 10.X.X.200:vmm/vm-501bf2f2-vnejvnje/nic-1616/vnic-stats
2021-05-20 16:42:01,175 - INFO - VM-FEX not supported. Skipping. 10.X.X.200:vmm/vm-501bf2f2-vnejvnje/nic-1616/vnic-stats

Current release is 2.2(2c). May be this is the reason?

**Comment by paregupt** [comment]
Hi Vitaly

Is there something different about this vnic? You can run the 

`python3.6 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt dict -vvv influxdb-lp`

Check the lines before line 210 and see what may be different about this vnic? I don't believe 2.2(2c) version can cause this.
AFAIK, VM-FEX is an old feature not being used anymore. Thoughts on this?
Do you have any other domain working with UTM?

Thx

**Comment by vevdokimov04041976** [comment]
Hi Paresh,
Output of "python3.6 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt -vvv influxdb-lp" is attached.
[UTM_output_210521.txt](https://github.com/paregupt/ucs_traffic_monitor/files/6523785/UTM_output_210521.txt)

It looks like service_profile name is longer. Nothing else.

Config in /etc/telegraf/telegraf.conf:
[[inputs.exec]]
   interval = "60s"
   commands = [
       "python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt influxdb-lp -vv",
   ]
   timeout = "50s"
   data_format = "influx"
   
   No, this is the first installation. 
   
   You wrote "Check the lines before line 210" - this mean  checking lines upper 210 in ucs_traffic_monitor.py? 
   
 Thanks in advance

**Comment by vevdokimov04041976** [comment]
May be this is the reason:
...
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=nic3,peer_type=IOM,peer=IOM-2,peer_port=2/13,fi_id=B bytes_rx_delta=52960,bytes_tx_delta=0,errors_rx_delta=0,errors_tx_delta=0,dropped_rx_delta=0,dropped_tx_delta=0

VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=dynamic-prot-001,peer_type=IOM,peer=IOM-1,peer_port=1/13,fi_id=A 
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=dynamic-prot-002,peer_type=IOM,peer=IOM-2,peer_port=2/13,fi_id=B 
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=dynamic-prot-003,peer_type=IOM,peer=IOM-1,peer_port=1/13,fi_id=A 
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=dynamic-prot-004,peer_type=IOM,peer=IOM-2,peer_port=2/13,fi_id=B 
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-4,service_profile=besx3,transport=Eth,vif_name=dynamic-prot-005,peer_type=IOM,peer=IOM-1,peer_port=1/13,fi_id=A 
Servers,domain=10.x.x.200,chassis=chassis-2,id=blade-3,location=City,service_profile=besx2,type=blade admin_state="in-service",association="associated",operability="operable",oper_state="ok",oper_state_code=0,memory=196608,model="UCSB-B200-M3",num_adaptors=1,num_cores=16,num_cpus=2,num_vEths=37,num_vFCs=0,serial="FCH18247XBC"
VnicStats,domain=10.x.x.200,adaptor=adaptor-1,chassis=chassis-2,domain_name=City,location=City,server=blade-3,service_profile=besx2,transport=Eth,vif_name=nic0,peer_type=IOM,peer=IOM-1,peer_port=1/09,fi_id=A bytes_rx_delta=86482,bytes_tx_delta=19137,errors_rx_delta=0,errors_tx_delta=0,dropped_rx_delta=0,dropped_tx_delta=0

...

This VnicStats hasn't data.

**Comment by vevdokimov04041976** [comment]
Dear Paresh, 
This issue can be closed. 
The collecting data for "vif_name=dynamic-prot-" was stopped.

**Comment by vevdokimov04041976** [comment]
Thank you
