### ISSUE TITLE
upgrade_utm.sh doesn't upgrade Grafana dashboards with https - works with http

### ISSUE THREAD

**Issue by slgta** [paregupt/ucs_traffic_monitor#59]
I am getting jq errors when using the upgrade script to upgrade the dashboard
I did some debugging and found out that neither $location_uid and $locations have a value
...... locations_uid=${utm_dashboard_arr["locations"]} .... and therefore the rest didn't work.
Any idea what I have done wrong?

Here is the output of the dashboard upgrade part .....

---------------------------
First, let's backup your existing UTM dashboards
I have taken a backup of your existing UTM dashboards in /usr/local/telegraf/grafana/dashboards_5114061121
---------------------------
Now, I will try to upgrade UTM dashboards. 
Are you sure: (y/n)y
Upgrading chassis_pause             -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading service_profile           -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading domain_overview           -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading domain_traffic            -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading chassis_traffic           -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading local_sys                 -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading locations                 -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Upgrading ingress_congestion        -- in Folder     -- with ID     -- to UTM version 5  
jq: error: syntax error, unexpected $end (Unix shell quoting issues?) at <top-level>, line 1:
.dashboard.id =                
jq: 1 compile error
jq: error: syntax error, unexpected ',' (Unix shell quoting issues?) at <top-level>, line 1:
. + { folderId: , overwrite:true }                
jq: 1 compile error
.
Done

UTM dashboards upgraded
---------------------------
Update home dashboard to ID 1 ...

That is all.
---------------------------
...
---------------------------
Bye - Kiara.
---------------------------

**Comment by paregupt** [comment]
Looks like it is unable to read the dashboard id from the existing dashboards. Please make sure you have existing dashboards. 

Check the content of files in /usr/local/telegraf/grafana/dashboards_5114061121

Can you please pull the latest and try again?

**Comment by slgta** [comment]
Thanks I will pull from git and try again.  But here are the file on that folder (all empty)....

utm@CLSCAIBMUTMP01 ~]$ ls -al /usr/local/telegraf/grafana/dashboards_5114061121
total 4
drwxr-xr-x.  2 root root  218 Jun 11 14:52 .
drwxr-xr-x. 25 root root 4096 Jun 11 14:52 ..
-rw-r--r--.  1 root root    0 Jun 11 14:52 chassis_pause.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 chassis_traffic.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 domain_overview.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 domain_traffic.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 ingress_congestion.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 local_sys.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 locations.json
-rw-r--r--.  1 root root    0 Jun 11 14:52 service_profile.json

**Comment by slgta** [comment]
same result after a fresh git clone.

btw, our team have configured the server to use https so I have to update the upgrade script for those four lines that has "http://$GRAFANA_USER:$GRAFANA_PASSWORD@localhost:3000" to use https.   But I don't think that is causing the jq errors.

**Comment by paregupt** [comment]
The empty files explain the jq error. Something is preventing the fetching of existing dashboards. Few options:

* Try running the curl command manually to find the error
* You can update manually or import the new dashboards manually in Grafana using the browser.

**Comment by slgta** [comment]
thanks again. 
I change grafana back to http temporary and the upgrade script works now.
Can you try on your setup to see if you can get grafana on https and still be able to upgrade utm dashboard?

**Comment by paregupt** [comment]
I see the same issue with https. Will look into it. Thanks for reporting. Glad you were able to upgrade with http. Please also verify the UI to make sure that the upgrade really went thru.

**Comment by slgta** [comment]
Thanks.  I think the dashboard did upgraded successfully.  We used to have problem in the location dashboard where all location showup in the top 10 widget ...doesn't matter which location we select in the drop down filter at the top.  But after this dashboard upgrade, the filter seems to be working correctly.

**Comment by slgta** [comment]
This is a wonderful tool by the way.   Thank you are making this available.

**Comment by paregupt** [comment]
yeah, I noticed that issue and fixed it in the latest while getting ready to UTM v0.6
Glad you like it.
