### ISSUE TITLE
UCS Domain Showing IP

### ISSUE THREAD

**Issue by neddyuk** [paregupt/ucs_traffic_monitor#62]
When looking at one of the other landing pages like UCS Domain Overview or domain traffic etc is there anyway to get the top left hand corner UCS domain dropdown to display the Domain rather than IP address?

Sorry if this has been answered before.

**Comment by paregupt** [comment]
For this, in the input file, change the IP address of the Domains by their DNS names. Obviously, the UTM server/VM should be able to resolve Names to IP. After making this change, both IP and DNS names will show up in UTM. To resolve this condition, drop all the data and start fresh or just let it be there. As it gets older, it will stop being shown on UTM.

**Comment by neddyuk** [comment]
Thanks, just one more question how do you flush all the old data?

**Comment by paregupt** [comment]
Can you please open a new issue asking for : how do you flush all the old data?
Just want to keep the documentation clean for others who may be looking for this info in the future. I will reply asap.
