### ISSUE TITLE
How to Delete Specific Records from the DB?

### ISSUE THREAD

**Issue by mnagy7** [paregupt/ucs_traffic_monitor#64]
Is there is an easy way to delete a couple of locations and UCS domains I added by mistake from the DB?.. I have removed it from the configuration test files but I still can see it on the dashboard!

Great work by the way :)

**Comment by paregupt** [comment]
Did it work?

**Comment by mnagy7** [comment]
I did not have time to test it yet. I will let you know once I do. Thanks for asking.

**Comment by paregupt** [comment]
Closing this issue. Feel free to open it again if the problem persists or a newer issue for a newer problem.
