### ISSUE TITLE
able to create OVA for v0.6?

### ISSUE THREAD

**Issue by toshitaka91164** [paregupt/ucs_traffic_monitor#65]
I have trouble upgrading the version from v0.3 to v0.6. it will be great to compile another OVA :)
Able to assist on this?

**Comment by paregupt** [comment]
What's the issue you are running into? I can certainly help you in that which may be far more faster than creating and testing a new OVA.

**Comment by toshitaka91164** [comment]
i am getting some issue using the automated upgrade script 
May I access the Internet now? (y to keep me going, n to install them manually):y
---------------------------
Downloading and upgrading Grafana ...
--2021-09-08 00:16:49-- https://dl.grafana.com/oss/release/grafana-7.5.7-1.x86_64.rpm
Resolving dl.grafana.com (dl.grafana.com)... 151.101.42.217, 2a04:4e42:a::729
Connecting to dl.grafana.com (dl.grafana.com)|151.101.42.217|:443... connected.
Unable to establish SSL connection.
---------------------------
I could not make that work
---------------------------
Downloading and upgrading Telegraf ...
--2021-09-08 00:16:49-- https://dl.influxdata.com/telegraf/releases/telegraf-1.18.3-1.x86_64.rpm
Resolving dl.influxdata.com (dl.influxdata.com)... 52.222.158.115, 52.222.158.92, 52.222.158.103, ...
Connecting to dl.influxdata.com (dl.influxdata.com)|52.222.158.115|:443... connected.
Unable to establish SSL connection.
---------------------------
I could not make that work
---------------------------
Downloading and upgrading other packages ...
---------------------------
Error: ✗ Failed to send request: Get https://grafana.com/api/plugins/repo/agenty-flowcharting-panel: read tcp 10.195.176.54:51822->34.120.177.193:443: read: connection reset by peer
---------------------------
I could not make that work
---------------------------
Error: ✗ Failed to send request: Get https://grafana.com/api/plugins/repo/michaeldmoore-multistat-panel: read tcp 10.195.176.54:51824->34.120.177.193:443: read: connection reset by peer
---------------------------
I could not make that work
---------------------------

**Comment by toshitaka91164** [comment]
seems like it is not able to get all the required update files using https...

**Comment by paregupt** [comment]
Does this machine have internet connectivity? If not, you an would load the packages manually and upgrade one by one. The upgrade script is just a shell script. Try following the same sequence of steps.

**Comment by toshitaka91164** [comment]
the machine have internet connectivity...if using the manually step, i am not sure what is the right way to update based on the steps given below:

If this machine can't reach the Internet, please:
  1. Download and install https://dl.grafana.com/oss/release/grafana-7.5.7-1.x86_64.rpm
      1.1. Earlier versions of Grafana will work with reduced functionality
  2. Download and install https://grafana.com/api/plugins/agenty-flowcharting-panel/versions/0.9.0/download
      2.1. Minimum required version 0.9
  3. Download and install https://grafana.com/api/plugins/michaeldmoore-multistat-panel/versions/1.7.1/download
      3.1. Minimum required version 1.4.1. UTM v0.6 onwards doesn't need Multistat panel
  4. Restart Grafana: systemctl restart grafana-server
  5. Download and install wget https://dl.influxdata.com/telegraf/releases/telegraf-1.18.3-1.x86_64.rpm
  6. Restart Telegraf: systemctl restart telegraf

for step 2 and 3 how do i proceed to update these?

**Comment by paregupt** [comment]
For steps 2 and 3, download the zip files and extract them in /var/lib/grafana/plugins. This directory should have existing directories with the same names. Overwrite everything.

After this, run the upgrade script again to update the dashboards. If the script doesn't work, delete the existing dashboards in Grafana and import the Dashboard json files one at a time.

**Comment by paregupt** [comment]
Were you able to make it work?

**Comment by toshitaka91164** [comment]
thanks for the advices....i will follow up on the upgrades step when i have some time..i will proceed to close this issue now
