### ISSUE TITLE
UCS Domain not updated with new domain information

### ISSUE THREAD

**Issue by toshitaka91164** [paregupt/ucs_traffic_monitor#67]
I have updated the correct domains and credential in 
/usr/local/telegraf/ucs_domains_group_1.txt or
/usr/local/telegraf/ucs_domains_group_2.txt

but the dashboard still not showing new domains but still showing old domains that i removed.

restarted the whole VM but it is not working.

**Comment by toshitaka91164** [comment]
2021-09-09T08:24:50Z E! [inputs.exec] Error in plugin: exec: Command timed out. for command 'python3 /usr/local/telegraf/ucs_traffic_monitor.py /usr/local/telegraf/ucs_domains_group_1.txt influxdb-lp -vv':

**Comment by paregupt** [comment]
The UTM error logs should tell you more. Check in /var/log/telegraf/ucs_traffic_monitor

**Comment by paregupt** [comment]
Is it working now?

**Comment by toshitaka91164** [comment]
this is working now after the we break up the number of domains into smaller size files
in /usr/local/telegraf/ directory.
