### ISSUE TITLE
Error in plugin: metric parse error: exoected field at 882.58: 

### ISSUE THREAD

**Issue by lebluesman** [paregupt/ucs_traffic_monitor#68]
hi 
i was able to add 2 UCS and they work fine
on the next 3 UCS i tryied to add i m getting this error: 
Error in plugin: metric parse error: exoected field at 882.58: 
i tried to add on the same file and also on diffrent files
no error on ucs_traffic_monitor_ucs_doomains_group_1.log

**Comment by paregupt** [comment]
- Make sure you are running the latest. 
- Try running only the problematic domain.
- Share the logfile with me. 
- Run the script manually and share the output of line 882. If fine to email me the sensitive logfile and script output.

**Comment by mahdidahmani** [comment]
sure what script should i run manyally ? 
please share your @Cisco  email so i can send you the logs

**Comment by mahdidahmani** [comment]
Actuallay i found the issue ! it was a sepace  on the location name [] 
how can i delete a location from the DB/graphana ?
