### ISSUE TITLE
Areas on locations page under Top 10 FI Uplink ports show no data

### ISSUE THREAD

**Issue by somersbd** [paregupt/ucs_traffic_monitor#72]
Just installed a new v3 ova and updated to 6.0. I get unrealiable results from the Locations page under the Top 10 FI Uplink ports. When the page first loads one column might show the No data result and then when refreashed it moves to a different column and shows No data.

I have three domains, 24 chassis and 182 serves. I have my original v3 environmnet running as well and do not get this same result from it.

**Comment by paregupt** [comment]
Do you still see the issue? If yes, can you please share more details?

**Comment by jackycsie** [comment]
I also have this issue.
But when I upgrade grafana.
I can see the data.

**Comment by paregupt** [comment]
I hope this issue got resolved.
