### ISSUE TITLE
Displaying Hostnames

### ISSUE THREAD

**Issue by ThomasMcDo** [paregupt/ucs_traffic_monitor#75]
Is it possible to display the hostname of the UCSM IP address instead of the IP address. All the IP's are able to resolve via DNS.

**Comment by jackycsie** [comment]
I use OVF file.
My experience is you can ping your DNS first.
If you can't ping your DNS FI.
You can apply your nameserver to /etc/resolv.conf then go to /usr/local/telegraf add user DNS FI name.
it's should be work.

**Comment by paregupt** [comment]
Closing this issue. Hope those comments fixed your problem. Feel free to open a new issue.
