### ISSUE TITLE
Is there any plan to support CentOS 8 or later (Stream) ? <eom>

### ISSUE THREAD

**Issue by slgta** [paregupt/ucs_traffic_monitor#76]

**Comment by paregupt** [comment]
It should just work. You can install all the packages by yourself. Alternatively, ansible install on CentOS 8 should be available soon. BTW, there isn't any support for any of UTM :)

**Comment by slgta** [comment]
It is not working.  We tried to upgrade the existing UTM VM to CentOS 8 Stream ...the OS upgrade went ok, but after that, UTM stopped collecting data from UCSM.   We end up having to redeploy the UTM OVA again to restore our service.
